### ISSUE TITLE
mixup with epsilon numbers?

### ISSUE THREAD

**Issue by ceedriic** [biovault/biovault_bfloat16#3]
I was just looking at the code, and it seem bfloat16_epsilon doesn't match the table:

	// According to John D. Cook, 15 November 2018,
	// Comparing bfloat16 range and precision to other 16-bit numbers:
	//
	// |--------+------------|
	// | Format |    Epsilon |
	// |--------+------------|
	// | FP32   | 0.00000012 |
	// | FP16   | 0.00390625 |
	// | BF16   | 0.03125000 |
	// |--------+------------|
	// https://www.johndcook.com/blog/2018/11/15/bfloat16/

	const auto bfloat16_epsilon = 0.00390631007f;

**Comment by N-Dekker** [comment]
@ceedriic Thank you very much for your observation, Cédric! Indeed, I made a mistake regarding epsilon. My `bfloat16_epsilon` should have matched the table by John D. Cook, but clearly it did not! Then apparently John adjusted the table, as it currently says at https://www.johndcook.com/blog/2018/11/15/bfloat16

    |--------+------------|
    | Format |    Epsilon |
    |--------+------------|
    | FP32   | 0.00000012 |
    | FP16   | 0.00097656 |
    | BF16   | 0.00781250 |
    |--------+------------|

A previous version of John's blog entry may still be at https://archive.org, if you're interested. But I believe the current one is right.

Which still does not match "my" `bfloat16_epsilon`, as I was also wrong! I'm just about to merge a fix onto the master that should address this issue. Thanks again!

**Comment by N-Dekker** [comment]
[Update] I just merged this commit to the master: "Fix bfloat16.Epsilon unit test, address issue #3 (mixup with epsilon)", https://github.com/biovault/biovault_bfloat16/commit/2e056bf7ff5257351b70116fac2006ac525144e0
@ceedriic Cédric, can you please check if it does indeed fix this issue?

**Comment by N-Dekker** [comment]
I'll just close this issue now, as it is addressed by https://github.com/biovault/biovault_bfloat16/commit/2e056bf7ff5257351b70116fac2006ac525144e0 @ceedriic Please reopen the issue if you think it isn't entirely resolved!
